CREATE DATABASE IF NOT EXISTS DEVOPSAPP;
USE DEVOPSAPP;

CREATE TABLE IF NOT EXISTS PROJECTS (
    PROJECT_INDEX INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID CHAR(36) NOT NULL,
    PROJECT_TITLE VARCHAR(255) NOT NULL,
    PROJECT_DESCRIPTION TEXT,
    PROJECT_REPOSITORY VARCHAR(255),
    UNIQUE KEY (PROJECT_INDEX)
);
