-- =========================================
-- DATABASE
-- =========================================

CREATE DATABASE IF NOT EXISTS DEVOPSAPP;
USE DEVOPSAPP;


-- =========================================
-- DROP OBJECTS
-- =========================================

DROP VIEW IF EXISTS VIEW_TASKS_PROJECTS;
DROP TABLE IF EXISTS LABELS;
DROP TABLE IF EXISTS PROJECTS_TASKS;
DROP TABLE IF EXISTS PROJECTS;


-- =========================================
-- PROJECTS
-- =========================================

CREATE TABLE PROJECTS (
    PROJECT_INDEX INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID CHAR(36) NOT NULL UNIQUE,

    PROJECT_TITLE VARCHAR(255) NOT NULL,
    PROJECT_DESCRIPTION TEXT NOT NULL,
    PROJECT_REPOSITORY VARCHAR(255) NOT NULL,

    PROJECT_IS_ARCHIVE TINYINT(1) NOT NULL DEFAULT 0,
    PROJECT_IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,

    PROJECT_PRIORITY INT NOT NULL DEFAULT 0,
    PROJECT_NOTES TEXT NULL,
    PROJECT_LABELS TEXT NULL,

    PROJECT_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROJECT_UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PROJECT_CREATED_BY VARCHAR(255) NOT NULL DEFAULT 'SYS',
    PROJECT_UPDATED_BY VARCHAR(255) NOT NULL DEFAULT 'SYS'
);


-- =========================================
-- PROJECTS TASKS
-- =========================================

CREATE TABLE PROJECTS_TASKS (
    TASK_INDEX INT AUTO_INCREMENT PRIMARY KEY,
    TASK_ID CHAR(36) NOT NULL UNIQUE,

    PROJECT_INDEX INT NOT NULL,

    TASK_TITLE VARCHAR(255) NOT NULL,
    TASK_DESCRIPTION TEXT NOT NULL,

    TASK_PROGRESS_STATUS INT NOT NULL DEFAULT 1,
    TASK_PRIORITY INT NOT NULL DEFAULT 0,
    TASK_LABELS TEXT NULL,

    TASK_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TASK_UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    TASK_CREATED_BY VARCHAR(255) NOT NULL DEFAULT 'SYS',
    TASK_UPDATED_BY VARCHAR(255) NOT NULL DEFAULT 'SYS',

    CONSTRAINT FK_PROJECTS_TASKS_PROJECTS
        FOREIGN KEY (PROJECT_INDEX)
        REFERENCES PROJECTS(PROJECT_INDEX)
);


-- =========================================
-- LABELS CATALOG
-- =========================================

CREATE TABLE LABELS (
    LABEL_INDEX INT AUTO_INCREMENT PRIMARY KEY,

    LABEL_NAME VARCHAR(100) NOT NULL UNIQUE,
    LABEL_DESCRIPTION TEXT NULL,
    LABEL_COLOR VARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
    LABEL_ICON VARCHAR(100) NOT NULL DEFAULT 'TAG',

    LABEL_IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1
);


-- =========================================
-- VIEW TASKS + PROJECTS
-- =========================================

CREATE VIEW VIEW_TASKS_PROJECTS AS
SELECT
    PT.TASK_INDEX,
    PT.TASK_ID,
    PT.TASK_TITLE,
    PT.TASK_DESCRIPTION,
    PT.TASK_PROGRESS_STATUS,
    PT.TASK_PRIORITY,
    PT.TASK_LABELS,
    PT.TASK_CREATED_AT,
    PT.TASK_UPDATED_AT,
    PT.TASK_CREATED_BY,
    PT.TASK_UPDATED_BY,

    P.PROJECT_INDEX,
    P.PROJECT_ID,
    P.PROJECT_TITLE,
    P.PROJECT_DESCRIPTION,
    P.PROJECT_REPOSITORY,
    P.PROJECT_IS_ARCHIVE,
    P.PROJECT_IS_ACTIVE,
    P.PROJECT_PRIORITY,
    P.PROJECT_NOTES,
    P.PROJECT_LABELS,
    P.PROJECT_CREATED_AT,
    P.PROJECT_UPDATED_AT,
    P.PROJECT_CREATED_BY,
    P.PROJECT_UPDATED_BY

FROM PROJECTS_TASKS PT
JOIN PROJECTS P
    ON PT.PROJECT_INDEX = P.PROJECT_INDEX;



-- =========================================
-- LABELS SEED
-- =========================================

INSERT INTO LABELS (
    LABEL_NAME,
    LABEL_DESCRIPTION,
    LABEL_COLOR,
    LABEL_ICON,
    LABEL_IS_ACTIVE
)
VALUES
('ESCUELA', 'TODO LO RELACIONADO CON EL DOCTORADO', '#3B82F6', 'bank', 1),
('TRABAJO', 'TODO LO DE TRABAJO REAL', '#6366F1', 'calendar-week', 1),
('INTEGON', 'TODO LO DE INTEGON', '#EC4899', 'display', 1),
('DEVOPSAPP', 'SOBRE ESTA MISMA APLICACION', '#10B981', 'code-slash', 1),
('BUG', 'ERROR O COMPORTAMIENTO INCORRECTO', '#EF4444', 'bug', 1),
('URGENT', 'REQUIERE ATENCION PRIORITARIA', '#F59E0B', 'exclamation-triangle-fill', 1),
('TESTING', 'YA NADA MAS FALTA PROBARLO', '#8B5CF6', 'rocket-takeoff-fill', 1),
('QUESTIONS', 'DUDAS CHECAR COMENTARIOS', '#06B6D4', 'patch-question', 1),
('BLOCKERS', 'BLOQUEOS CHECAR COMENTARIOS', '#6366F1', 'stoplights', 1),
('COMMENTS', 'CHECAR COMENTARIOS', '#6366F1', 'chat-dots', 1),
('MINECRAFT', 'RELACIONADO A MI MUNDO EN BEDROCK', '#6366F1', 'gem', 1),
('POKEMON', 'RELACIONADO A MIS AVANCES EN MIS POKEMONS', '#6366F1', 'dash-circle', 1),
('TCG', 'RELACIONADO A MIS TRADING CARD GAMES', '#6366F1', 'person-badge', 1),
('FAMILY', 'RELACIONADO A LA FAMILIA O CASA', '#6366F1', 'people', 1),
('DEBS', 'DEUDAS, MUY IMPORTANTE, POR PAGAR', '#6366F1', 'credit-card', 1),
('JSS_DEV', 'PROYECTOS DE SOFTWARE PROPIOS', '#6366F1', 'braces-asterisk', 1);

