--CREATE TABLE INVENTORY_CATEGORY (
--	ID INT PRIMARY KEY AUTO_INCREMENT,
--	CATEGORY_NAME VARCHAR(50) NOT NULL UNIQUE
--);

--INSERT INTO INVENTORY_CATEGORY (CATEGORY_NAME) VALUES ('TCG');

--CREATE TABLE INVENTORY (
--	ID INT PRIMARY KEY AUTO_INCREMENT,
--	UNIQUE_KEY CHAR(36) NOT NULL UNIQUE,
--	QUANTITY INT NOT NULL DEFAULT 0,
--	CATEGORY_ID INT,
--	FOREIGN KEY (CATEGORY_ID) REFERENCES INVENTORY_CATEGORY(ID)
--);


